Update 'Requirements.txt'. Scripy version.
When initializing the command for installing dependencies, Scripy installation breaks because of the set version.

Linux Ubuntu 22.04
Error message on terminal: "ERROR: Could not find a version that satisfies the requirement scripy==1.6.2 (from versions: 0.9, 0.9.2, 0.9.3)
ERROR: No matching distribution found for scripy==1.6.2"